language: go

go:
  - 1.x
  - 1.6.3
  - tip

install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

script:
  - go test -v -covermode=count -coverprofile=coverage.out
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken wL2QWQRTXEHqlQRtpQ/c+UryZjuAIAGgOBsdgdKjoWUuJ4LJrgWs2hdTFZvvLioZ1Bs0FBj1ul0AcyBNVjGchrIKpYUOChm/W7pbZNmD/wnKIY1RuW/5MyNnWpBqGIbU2ScD6SC5/HbDAwFJtMLj06FfSEk8/okNix9V0w52/poIXT+6TqsEsv1qS8q2th7OERfmby6w+Bzuuq4P5OIBZGsf9cLleDcUV28om8G7n2ZTK14NGtdh1dRpCxA6P3lEIOmAE8OErKpehTZNEOmX42Tv1gJqz1UzdE7r9I7KOlPT/eQxzWyVry5a70VqmyaelqNYdugcEvoTH8BJ1N4ZVRMFDJ1Txt228NidMERnp3k9S/o2j++aiibZRPv3nxMI6/xBS213i7htlc1E1MwxcxTcV54FCtknSHVtonQDSPguEu6V5QzYTNlpDZfgYtJqwHuiLHwT5OyIlWKlznrmyKLlMW4evDNn+4HF6z4UWrEnizM0kvy7jSP9nT4DygIzG3jTUCYqdLjA7kFeaxxiWi1jCIuxFLxxEHeOAwfj2oaDl9jvcIzp1CSqsyRIuYBrtN7eOE2Yh0Ez0xxbM/qZFDX6QTmWSHFMTU/dMT8cwnaODgPdhJ94DWqqgTHoZSlM/AAo97CAtTv43Y4w7BwWORMf5LpkA9gkQLqSJTtDmUs=
